python manage.py migrate --run-syncdb

Session data corrupted
python -c "import secrets; print(secrets.token_urlsafe(32))"
from django.core.management.utils import get_random_secret_key
print(get_random_secret_key())
